[package]
edition = "2024"
name = "hello"
version = "0.1.0"
authors = ["Michael Sch√∂ttner <michael.schoettner@hhu.de>"]

[lib]
crate-type = ["staticlib"]
path = "src/hello.rs"

[dependencies]
usrlib = { path = "../../usrlib" }