######################################
# Environment variables
######################################

[env.development]
CARGO_CFG_TARGET_FAMILY = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/hhu_tosr_app.json"
BUILD_DIRECTORY = "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/hhu_tosr_app/debug"
CARGO_BUILD_OPTION = "--lib"

[env.production]
CARGO_CFG_TARGET_FAMILY = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/hhu_tosr_app.json"
BUILD_DIRECTORY = "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/hhu_tosr_app/release"
CARGO_BUILD_OPTION = "--release"

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
RUST_TARGET_PATH = "${CARGO_MAKE_WORKING_DIRECTORY}"
SOURCE_DIRECTORY = "${CARGO_MAKE_WORKING_DIRECTORY}/src"
LINKER_FILE = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/apps/linker.ld"
RUST_OBJECT = "${BUILD_DIRECTORY}/lib${CARGO_MAKE_PROJECT_NAME}.a"
APPLICATION_ELF = "${BUILD_DIRECTORY}/${CARGO_MAKE_PROJECT_NAME}.elf"
APPLICATION_FLAT = "${BUILD_DIRECTORY}/${CARGO_MAKE_PROJECT_NAME}"

######################################
# Build tasks
######################################

# Default task
[tasks.default]
alias = "link"

# 
# Compiling Rust sources
#
[tasks.compile]
command = "cargo"
args = [ "build", "-Z", "build-std=core,alloc", "-Z", "build-std-features=compiler-builtins-mem", "--target", "${CARGO_CFG_TARGET_FAMILY}", "${CARGO_BUILD_OPTION}" ]

#
# Linking
#
[tasks.link-elf]
command = "${LINKER}"
args = [ "-n", "-T", "${LINKER_FILE}", "-o", "${APPLICATION_ELF}", "${RUST_OBJECT}", "-z", "noexecstack" ]
dependencies = [ "compile" ]

[tasks.link]
command = "${OBJCOPY}"
args = [ "-O", "binary", "${APPLICATION_ELF}", "${APPLICATION_FLAT}", "--set-section-flags", ".bss=alloc,load,contents" ]
dependencies = [ "link-elf" ]